#!/bin/bash
#
# Script to simplify local testing. 
#    Requires sauce-connect tunnel to be active before running this script. 
#    Requires editing the command with the SauceLab credentials as well.
# Usage:   ./test <test class(es)>
# Examples:
#     Run every test under the namespace pt.arquivo.tests.webapp.replay.menu:
#     ./test pt.arquivo.tests.webapp.replay.menu.**  
#     Run the datepicker test:
#     ./test pt.arquivo.tests.webapp.datepicker.DatePickerTest
#     Run the datepicker test and the memorial test:
#     ./test pt.arquivo.tests.webapp.datepicker.DatePickerTest,pt.arquivo.tests.memorial.MemorialTest

WIN_CHROME='{"platform":"Windows 10", "browser":"Chrome", "browser-version":"latest", "resolution":"1280x960"}'
WIN_FIREFOX='{"platform":"Windows 10", "browser":"Firefox", "browser-version":"latest", "resolution":"1280x960"}'
WIN_EDGE='{"platform":"Windows 10", "browser":"Edge", "browser-version":"latest", "resolution":"1280x960"}'
MAC_CHROME='{"platform":"MacOS", "browser":"Chrome", "browser-version":"latest", "resolution":"1280x960"}'
MAC_FIREFOX='{"platform":"MacOS", "browser":"Firefox", "browser-version":"latest", "resolution":"1280x960"}'
MAC_SAFARI='{"platform":"MacOS", "browser":"Safari", "browser-version":"latest", "resolution":"1280x960"}'
AND_CHROME='{"platform":"Android", "platform-version":"12.0", "browser":"Chrome", "device":"Android GoogleAPI Emulator", "automation-name":"UIAutomator2"}'
IOS_SAFARI='{"platform":"iOS", "platform-version":"15.4", "browser":"Safari", "device":"iPhone Simulator", "automation-name":"XCUITest"}'

WINDOWS="$WIN_CHROME , $WIN_FIREFOX , $WIN_EDGE"
MAC="$MAC_CHROME , $MAC_FIREFOX , $MAC_SAFARI"
ANDROID="$AND_CHROME"
IOS="$IOS_SAFARI"

DESKTOP="$WINDOWS , $MAC"
MOBILE="$ANDROID , $IOS"

#Edit this to change test devices:
export SAUCE_ONDEMAND_BROWSERS="[ $WIN_CHROME , $MOBILE ]"

mvn clean verify \
   -Djava.locale.providers=COMPAT,SPI \
   -Dtest.url=https://preprod.arquivo.pt \ 
   -Dtest.saucelabs.user=xxxxxx \                       #<------------ EDIT! -------------------
   -Dtest.saucelabs.key=xxxxx-xxxxx-xxxxx-xxxxx-xxxxx \ #<------------ EDIT! -------------------
   -Dtest.selenium.host=localhost \
   -Dtest.selenium.port=4444 \
   -Dit.test=$1
